language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t flashd2n/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true flashd2n/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-971140117512"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"