language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t flashd2n/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true flashd2n/docker-react npm run test -- --coverage