version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
  tests:
   build:
     context: .
     dockerfile: Dockerfile.dev
   volumes:
     - ./src:/home/node/app/src
   command: ["npm", "run", "test"]